config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/contact' => 'pages#contact'
  get '/business' => 'pages#business'
  get '/payment_success' => 'orders#payment_success'
  get '/payment_fail' => 'orders#payment_fail'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'account', sign_up: 'registration'},
              controllers: { registrations: 'registrations',}

  namespace :admin do
    resources :dashboards, only: :index
    resources :restaurants, except: [:new, :create, :edit] do
      member do
        get :menu
      end
    end
    resources :customers, except: [:new, :create, :edit] do
      member do
        get :orders
      end
    end
    resources :meals, except: [:index, :edit, :new]
  end

  namespace :api do
    namespace :v1 do
      post '/check' => 'sessions#check'
      post '/login' => 'sessions#login'
      post '/logout' => 'sessions#logout'
      post '/register' => 'registrations#create'
      post '/update_profile' => 'customers#update'
      post '/update_location' => 'customers#update_location'
      post '/fetch_info' => 'customers#fetch_info'
      post '/customer_orders' => 'orders#list_customer_orders'
      post '/current_order' => 'orders#current_order'
      post '/completed_orders' => 'orders#completed_orders'
      post '/current_status' => 'orders#current_status'
      post '/menu' => 'restaurants#menu'
      resources :restaurants, only: [:index, :show] do
        member do
          post :open
          post :close
        end
      end
      resources :orders, only: :create do
        member do
          post :approve
          post :decline
          post :ready
          post :on_the_way
          post :arrive
          post :deliver
          post :customer_order
          post :cancel
          post :is_ready
          post :is_approve
          post :is_paid
          post :pay
        end
      end
      resources :meals, only: :nil do
        member do
          post :enable
          post :disable
        end
      end
    end
  end

  resources :restaurants, only: [:edit, :update]
  resources :meals do
    member do
      post :enable
      post :disable
    end
  end
  resources :revenues, only: :index
  resources :orders, only: :nil do
    member do
      get :return
      post :return
      get :callback
      post :callback
      get :pay
    end
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_many :payments

  def self.search(search)
    where('name ILIKE :search', search: "%#{search}%")
  end

  enum status: [:Active, :Inactive]

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :check_if_admin
  before_action :set_customer, except: :index

  def index
    @customers = Customer.all.order("created_at DESC")
    if params[:search]
      @customers = Customer.search(params[:search]).order("created_at DESC")
    end
  end

  def show

  end

  def update
    if @customer.update(customer_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def orders
    @orders = @customer.orders
    if params[:search]
      @orders = Order.search(params[:search]).order("created_at DESC")
    end
  end

  def destroy

  end

  private

  def customer_params
    params.require(:customer).permit(:name, :plate_num, :phone, :car_desc, :status)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end

end

app/controllers/api/v1/customers_controller.rb
class Api::V1::CustomersController < Api::V1::BaseController
  before_action :authenticate_with_token!

  def update
    customer = current_user.customer
    if customer.update(customer_params)
      render json: customer, status: :ok
    else
      render json: {error: "Something went wrong...", is_success: false}
    end
  end

  # POST: customer update locations while on the way to pickup order
  def update_location
    customer = current_user.customer
    order = customer.orders.where(status: 5).last
    customer.update(location_params)
    # Check if customer location is within 50 meters from pickup location then change status from on the way to arrive.
    # Function to notify restaurant will built later
    if order
      distance = Geocoder::Calculations.distance_between([customer.lat,customer.long], [order.restaurant.latitude,order.restaurant.longitude])
      if distance <= 0.05
        order.update(status: 6)
        render json: {arrive: true}, status: :ok
      else
        render json: {arrive: false}, status: :ok
      end
    else
      render json: {error: "You either arrived or have no pending order..", is_success: false}
    end
  end

  def fetch_info
    customer = current_user.customer
    if customer
      render json: customer, status: :ok
    else
      render json: {error: "No user exist", is_success: false}
    end
  end

  private

  def customer_params
    params.permit(:name, :phone, :plate_num, :car_desc)
  end

  def location_params
    params.permit(:lat, :long)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper

  def last_location(lat, long)
    query = Geocoder.search("#{lat},#{long}").first
    if query
      return query.address
    else
      return "N/A"
    end
  end

end

app/views/admin/customers/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_tag(admin_customers_path, method: "get", id: "search-form") do %>
    <div class="col-md-6"><%= text_field_tag :search, params[:search], placeholder: "Search Customer", class: "form-control text" %></div>
    <div class="col-md-3"><%= submit_tag "Search", :name => nil, class:"btn btn-success btn-form"%></div>
    <%end%>
    <span class="col-md-3"><%= link_to "View All", admin_customers_path, class: "btn btn-success btn-info" %></span>
  </div>
  <div class="col-md-6"></div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Customers
        <br>
      </div>
      <div class="panel-body">
        <div>
          <div style="overflow-x:auto;">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>Plate Number</th>
                  <th>Vehicle Description</th>
                </tr>
              </thead>
              <tbody>
                <%@customers.each_with_index do |customer, index|%>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= link_to customer.name, admin_customer_path(customer) %></td>
                  <td><%= customer.phone %></td>
                  <td><%= customer.plate_num %></td>
                  <td><%= customer.car_desc %></td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/orders.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_tag(orders_admin_customer_path(@customer), method: "get", id: "search-form") do %>
    <div class="col-md-6"><%= text_field_tag :search, params[:search], placeholder: "Search Order", class: "form-control text" %></div>
    <div class="col-md-3"><%= submit_tag "Search", :name => nil, class:"btn btn-success btn-form"%></div>
    <%end%>
    <span class="col-md-3"><%= link_to "View All", orders_admin_customer_path(@customer), class: "btn btn-success btn-info" %></span>
  </div>
  <div class="col-md-6"></div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Orders
        <br>
      </div>
      <div class="panel-body">
        <div>
          <div style="overflow-x:auto;">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Order ID</th>
                  <th>Restaurant</th>
                  <th>Total</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <%@orders.each_with_index do |order, index|%>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= order.order_id %></td>
                  <td><%= order.restaurant.name %></td>
                  <td><%= order.total %></td>
                  <td><%= order.status %></td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="row">
  <div class="col-md-6"></div>
  <div class="col-md-6">
    <div class="pull-right">
      <%= link_to "View Orders", orders_admin_customer_path(@customer), class: "btn btn-normal btn-success" %>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Manage Customer
      </div>
      <div class="panel-body" style="padding-left:80px;padding-right:80px;">
        <%= form_for(@customer , url: admin_customer_path(@customer), method: :patch) do |f| %>
        <div class="row">
          <div class="col-md-12">
            <h4>Customer Details</h4>
            <div class="row">
              <div class="form-group pull-in clearfix">
                <div class="col-md-4">
                  <label>Name</label>
                  <%= f.text_field :name, class: 'form-control', placeholder:"Customer name", type:"text", required: true %>
                </div>
                <div class="col-md-4">
                  <label>Phone</label>
                  <%= f.text_field :phone, class: 'form-control', placeholder:"Customer phone", type:"text", required: true %>
                </div>
                <div class="col-md-4">
                  <label>Status</label>
                  <%= f.select :status, ['Active','Inactive'], required: true, class: "form-control" %>
                </div>
              </div>
            </div>
            <hr>
            <h4>Customer Vehicle Description</h4>
            <div class="row">
              <div class="form-group pull-in clearfix">
                <div class="col-md-6">
                  <label>Plate Number</label>
                  <%= f.text_field :plate_num, class: 'form-control', placeholder:"Customer Plate Number", type:"text", required: true %>
                </div>
                <div class="col-md-6">
                  <label>Description</label>
                  <%= f.text_field :car_desc, class: 'form-control', placeholder:"Customer Vehicle Desc", type:"text", required: true %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= f.submit "Update", class: "btn btn-normal btn-form"%>
          </div>
        </div>
        <% end %>
        <br><hr>
        <div class="row">
          <div class="col-md-12">
            <h4>Other Details</h4>
            <br>
            <div class="row">
              <div class="col-md-12">
                <table class="table">
                  <tbody>
                    <tr>
                      <th>Last Location</th>
                      <td>
                        <% if @customer.lat && @customer.long %>
                          <%= last_location(@customer.lat, @customer.long) %>
                        <% else %>
                          N/A
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <th>Last Order</th>
                      <td>
                        <% if @customer.orders.where(status: 8).last %>
                          <%= @customer.orders.where(status: 8).last.updated_at.strftime('%d %b %G') %>
                        <% else %>
                          N/A
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <th>Completed Orders</th>
                      <td><%= @customer.orders.where(status: 8).count %></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>