config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/contact' => 'pages#contact'
  get '/business' => 'pages#business'
  get '/payment_success' => 'orders#payment_success'
  get '/payment_fail' => 'orders#payment_fail'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'account', sign_up: 'registration'},
              controllers: { registrations: 'registrations',}

  namespace :admin do
    resources :dashboards, only: :index
    resources :restaurants, except: [:new, :create, :edit] do
      member do
        get :menu
      end
    end
    resources :customers, except: [:new, :create, :edit] do
      member do
        get :orders
      end
    end
    resources :meals, except: [:index, :edit, :new]
  end

  namespace :api do
    namespace :v1 do
      post '/check' => 'sessions#check'
      post '/login' => 'sessions#login'
      post '/logout' => 'sessions#logout'
      post '/register' => 'registrations#create'
      post '/update_profile' => 'customers#update'
      post '/update_location' => 'customers#update_location'
      post '/fetch_info' => 'customers#fetch_info'
      post '/customer_orders' => 'orders#list_customer_orders'
      post '/current_order' => 'orders#current_order'
      post '/completed_orders' => 'orders#completed_orders'
      post '/current_status' => 'orders#current_status'
      post '/menu' => 'restaurants#menu'
      resources :restaurants, only: [:index, :show] do
        member do
          post :open
          post :close
        end
      end
      resources :orders, only: :create do
        member do
          post :approve
          post :decline
          post :ready
          post :on_the_way
          post :arrive
          post :deliver
          post :customer_order
          post :cancel
          post :is_ready
          post :is_approve
          post :is_paid
          post :pay
        end
      end
      resources :meals, only: :nil do
        member do
          post :enable
          post :disable
        end
      end
    end
  end

  resources :restaurants, only: [:edit, :update]
  resources :meals do
    member do
      post :enable
      post :disable
    end
  end
  resources :revenues, only: :index
  resources :orders, only: :nil do
    member do
      get :return
      post :return
      get :callback
      post :callback
      get :pay
    end
  end

end

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px; min-height: 55px">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to admin_dashboards_path, class: "navbar-brand" do %>
          <%= image_tag "drivebuy_logo.png" %>
        <% end %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
          <li><%= link_to "Restaurant Login", new_user_session_path %></li>
          <li><a href="#early_access" class="btn btn-success btn-normal" style= "color: white; background-color: #12E3CE;">GET EARLY ACCESS</a></li>
          <!-- <li><%= link_to "Sign up", new_user_registration_path %></li> -->
          <% else %>
          <li><%= link_to "Restaurants", admin_restaurants_path %></li>
          <li><%= link_to "Customers", admin_customers_path %></li>
          <li><%= link_to "Reports", admin_restaurants_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
              role="button" aria-haspopup="true" aria-expanded="false">
              Admin <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <br>
  <div class="text-center">
    <div class="container text-center">
      <ul class="list-inline">
        <li class="list-inline-item">
          <a href="https://www.facebook.com/drivebuyMY/" target="_blank">
            <i class="fa fa-facebook-square fa-2x"></i>
          </a>
        </li>
      </ul>
    </div><br>
    <p>© 2017 Drivebuy Sdn. Bhd. All Rights Reserved.</p>
    <ul class="list-inline">
      <li class="list-inline-item">
        <a href="/privacy">Privacy</a>
      </li>
      <li class="list-inline-item">
        <a href="/terms">Terms</a>
      </li>
      <li class="list-inline-item">
        <a href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px; min-height: 55px">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "drivebuy_logo.png" %>
        <% end %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
          <li><%= link_to "For Business", business_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><a href="#early_access" class="btn btn-success btn-normal" style= "color: white; background-color: #12E3CE;">GET EARLY ACCESS</a></li>
          <!-- <li><%= link_to "Sign up", new_user_registration_path %></li> -->
          <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
              role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.restaurant.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your Menu", meals_path %></li>
              <li><%= link_to "Your Orders", root_path %></li>
              <li><%= link_to "Your History", root_path %></li>
              <li><%= link_to "Your Revenue", revenues_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Edit Restaurant", edit_restaurant_path(current_user) %></li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>