config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/contact' => 'pages#contact'
  get '/business' => 'pages#business'
  get '/payment_success' => 'orders#payment_success'
  get '/payment_fail' => 'orders#payment_fail'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'account', sign_up: 'registration'},
              controllers: { registrations: 'registrations',}

  namespace :admin do
    resources :dashboards, only: :index
    resources :restaurants, except: [:new, :create, :edit] do
      member do
        get :menu
      end
    end
    resources :customers, except: [:new, :create, :edit] do
      member do
        get :orders
      end
    end
    resources :meals, except: [:index, :edit, :new]
  end

  namespace :api do
    namespace :v1 do
      post '/check' => 'sessions#check'
      post '/login' => 'sessions#login'
      post '/logout' => 'sessions#logout'
      post '/register' => 'registrations#create'
      post '/update_profile' => 'customers#update'
      post '/update_location' => 'customers#update_location'
      post '/fetch_info' => 'customers#fetch_info'
      post '/customer_orders' => 'orders#list_customer_orders'
      post '/current_order' => 'orders#current_order'
      post '/completed_orders' => 'orders#completed_orders'
      post '/current_status' => 'orders#current_status'
      post '/menu' => 'restaurants#menu'
      resources :restaurants, only: [:index, :show] do
        member do
          post :open
          post :close
        end
      end
      resources :orders, only: :create do
        member do
          post :approve
          post :decline
          post :ready
          post :on_the_way
          post :arrive
          post :deliver
          post :customer_order
          post :cancel
          post :is_ready
          post :is_approve
          post :is_paid
          post :pay
        end
      end
      resources :meals, only: :nil do
        member do
          post :enable
          post :disable
        end
      end
    end
  end

  resources :restaurants, only: [:edit, :update]
  resources :meals do
    member do
      post :enable
      post :disable
    end
  end
  resources :revenues, only: :index
  resources :orders, only: :nil do
    member do
      get :return
      post :return
      get :callback
      post :callback
      get :pay
    end
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :meals
  has_many :orders
  has_many :payments

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search)
    where('name ILIKE :search', search: "%#{search}%")
  end

  enum status: [:Active, :Inactive]

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :check_if_admin
  before_action :set_restaurant, except: :index

  def index
    @restaurants = Restaurant.all.order("created_at DESC")
    if params[:search]
      @restaurants = Restaurant.search(params[:search]).order("created_at DESC")
    end
  end

  def show

  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def menu
    @foods = @restaurant.meals.where(meal_type: 0)
    @drinks = @restaurant.meals.where(meal_type: 1)
    @meal = Meal.new
    if params[:search]
      @foods = @restaurant.meals.where(meal_type: 0).search(params[:search]).order("created_at DESC")
      @drinks = @restaurant.meals.where(meal_type: 1).search(params[:search]).order("created_at DESC")
    end
  end

  def destroy

  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :latitude, :longitude, :prepare_time, :status)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/api/v1/restaurants_controller.rb
class Api::V1::RestaurantsController < Api::V1::BaseController
  before_action :authenticate_with_token!, except: [:index, :show]

  #----------------------Customer Actions----------------------#
  def index
    if params[:latitude].present? && params[:longitude].present?
      restaurants = Restaurant.where(open: true).near([params[:latitude],params[:longitude]],30)
      render json: restaurants, status: :ok
    else
      restaurants = Restaurant.where(open: true)
      render json: restaurants, status: :ok
    end
  end

  def show
    restaurant = Restaurant.find_by(id: params[:id])
    if restaurant
      restaurant_meals = restaurant.meals.where(available: true)
      render json: {meals: restaurant_meals, is_success: true}, status: :ok
    else
      render json: {error: "Restaurant not found", is_success: false}
    end
  end

  #----------------------Restaurant Actions----------------------#

  # restaurant to visible in customer app
  def open
    restaurant = current_user.restaurant
    restaurant.update(open: true)
    render json: {open: true}, status: :ok
  end

  # restaurant turn off visibility in customer app
  def close
    restaurant = current_user.restaurant
    restaurant.update(open: false)
    render json: {open: false}, status: :ok
  end

  # restaurant views all meals they offered
  def menu
    foods = current_user.restaurant.meals.where(meal_type: 0)
    drinks = current_user.restaurant.meals.where(meal_type: 1)
    render json: {foods: foods, drinks: drinks, is_success: true}, status: :ok
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant

  def edit

  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :prepare_time, :phone)
  end

  def set_restaurant
    @restaurant = current_user.restaurant
  end

end

app/views/admin/restaurants/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_tag(admin_restaurants_path, method: "get", id: "search-form") do %>
    <div class="col-md-6"><%= text_field_tag :search, params[:search], placeholder: "Search Restaurant", class: "form-control text" %></div>
    <div class="col-md-3"><%= submit_tag "Search", :name => nil, class:"btn btn-success btn-form"%></div>
    <%end%>
    <span class="col-md-3"><%= link_to "View All", admin_restaurants_path, class: "btn btn-success btn-info" %></span>
  </div>
  <div class="col-md-6"></div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Restaurants
        <br>
      </div>
      <div class="panel-body">
        <div>
          <div style="overflow-x:auto;">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Phone</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <%@restaurants.each_with_index do |restaurant, index|%>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= link_to restaurant.name, admin_restaurant_path(restaurant) %></td>
                  <td><%= restaurant.address %></td>
                  <td><%= restaurant.phone %></td>
                  <td>Open</td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/restaurants/menu.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_tag(menu_admin_restaurant_path(@restaurant), method: "get", id: "search-form") do %>
    <div class="col-md-6"><%= text_field_tag :search, params[:search], placeholder: "Search Meal", class: "form-control text" %></div>
    <div class="col-md-3"><%= submit_tag "Search", :name => nil, class:"btn btn-success btn-form"%></div>
    <%end%>
    <span class="col-md-3"><%= link_to "View All", menu_admin_restaurant_path(@restaurant), class: "btn btn-success btn-info" %></span>
  </div>
  <div class="col-md-6">
    <div class="pull-right">
      <%= render partial: "admin/meals/form" %>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Foods
        <br>
      </div>
      <div class="panel-body">
        <div>
          <div style="overflow-x:auto;">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Code</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Price</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <%@foods.each_with_index do |food, index|%>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= !food.code.blank? ? food.code : "N/A" %></td>
                  <td><%= link_to food.name, admin_meal_path(food) %></td>
                  <td><%= !food.desc.blank? ? food.desc : "N/A" %></td>
                  <td><%= food.price %></td>
                  <td>
                    <% if food.available? %>
                      Available
                    <% else %>
                      Unavailable
                    <% end %>
                  </td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Drinks
        <br>
      </div>
      <div class="panel-body">
        <div>
          <div style="overflow-x:auto;">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Code</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Price</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <%@drinks.each_with_index do |drink, index|%>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= !drink.code.blank? ? drink.code : "N/A" %></td>
                  <td><%= link_to drink.name, admin_meal_path(drink) %></td>
                  <td><%= !drink.desc.blank? ? drink.desc : "N/A" %></td>
                  <td><%= drink.price %></td>
                  <td>
                    <% if drink.available? %>
                      Available
                    <% else %>
                      Unavailable
                    <% end %>
                  </td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/restaurants/show.html.erb
<div class="row">
  <div class="col-md-6"></div>
  <div class="col-md-6">
    <div class="pull-right">
      <%= link_to "View Menu", menu_admin_restaurant_path(@restaurant), class: "btn btn-normal btn-success" %>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Manage Restaurant
      </div>
      <div class="panel-body" style="padding-left:80px;padding-right:80px;">
        <%= form_for(@restaurant , url: admin_restaurant_path(@restaurant), method: :patch) do |f| %>
        <div class="row">
          <div class="col-md-12">
            <h4>Restaurant Details</h4>
            <div class="row">
              <div class="form-group pull-in clearfix">
                <div class="col-md-4">
                  <label>Name</label>
                  <%= f.text_field :name, class: 'form-control', placeholder:"Restaurant name", type:"text", required: true %>
                </div>
                <div class="col-md-4">
                  <label>Phone</label>
                  <%= f.text_field :phone, class: 'form-control', placeholder:"Restaurant phone", type:"text", required: true %>
                </div>
                <div class="col-md-4">
                  <label>Prepare Time</label>
                  <%= f.select :prepare_time, ['10 minutes','15 minutes','20 minutes'], required: true, class: "form-control" %>
                </div>
              </div>
              <div class="form-group pull-in clearfix">
                <div class="col-md-4">
                  <label>Status</label>
                  <%= f.select :status, ['Active','Inactive'], required: true, class: "form-control" %>
                </div>
              </div>
            </div>
            <hr>
            <h4>Pickup Location</h4>
            <div class="row">
              <div class="form-group pull-in clearfix">
                <div class="col-md-12">
                  <label>Address</label>
                  <%= f.text_field :address, class: 'form-control', placeholder:"Restaurant Address", type:"text", required: true %>
                </div>
              </div>
              <div class="form-group pull-in clearfix">
                <div class="col-md-4">
                  <label>Latitude</label>
                  <%= f.text_field :latitude, class: 'form-control', placeholder:"Latitude", type:"text", required: true %>
                </div>
                <div class="col-md-4">
                  <label>Longitude</label>
                  <%= f.text_field :longitude, class: 'form-control', placeholder:"Latitude", type:"text", required: true %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= f.submit "Update", class: "btn btn-normal btn-form"%>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>