config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/terms' => 'pages#terms'
  get '/privacy' => 'pages#privacy'
  get '/contact' => 'pages#contact'
  get '/business' => 'pages#business'
  get '/payment_success' => 'orders#payment_success'
  get '/payment_fail' => 'orders#payment_fail'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'account', sign_up: 'registration'},
              controllers: { registrations: 'registrations',}

  namespace :admin do
    resources :dashboards, only: :index
    resources :restaurants, except: [:new, :create, :edit] do
      member do
        get :menu
      end
    end
    resources :customers, except: [:new, :create, :edit] do
      member do
        get :orders
      end
    end
    resources :meals, except: [:index, :edit, :new]
  end

  namespace :api do
    namespace :v1 do
      post '/check' => 'sessions#check'
      post '/login' => 'sessions#login'
      post '/logout' => 'sessions#logout'
      post '/register' => 'registrations#create'
      post '/update_profile' => 'customers#update'
      post '/update_location' => 'customers#update_location'
      post '/fetch_info' => 'customers#fetch_info'
      post '/customer_orders' => 'orders#list_customer_orders'
      post '/current_order' => 'orders#current_order'
      post '/completed_orders' => 'orders#completed_orders'
      post '/current_status' => 'orders#current_status'
      post '/menu' => 'restaurants#menu'
      resources :restaurants, only: [:index, :show] do
        member do
          post :open
          post :close
        end
      end
      resources :orders, only: :create do
        member do
          post :approve
          post :decline
          post :ready
          post :on_the_way
          post :arrive
          post :deliver
          post :customer_order
          post :cancel
          post :is_ready
          post :is_approve
          post :is_paid
          post :pay
        end
      end
      resources :meals, only: :nil do
        member do
          post :enable
          post :disable
        end
      end
    end
  end

  resources :restaurants, only: [:edit, :update]
  resources :meals do
    member do
      post :enable
      post :disable
    end
  end
  resources :revenues, only: :index
  resources :orders, only: :nil do
    member do
      get :return
      post :return
      get :callback
      post :callback
      get :pay
    end
  end

end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :restaurant
  has_many :order_details

  def self.search(search)
    where('name ILIKE :search', search: "%#{search}%")
  end

  enum meal_type: [:Food, :Drink]
end

app/controllers/admin/meals_controller.rb
class Admin::MealsController < ApplicationController
  before_action :check_if_admin
  before_action :set_meal, except: [:create]

  def show

  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def update
    @restaurant = Restaurant.find_by(id: @meal.restaurant_id)
    if @meal.update(meal_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_to menu_admin_restaurant_path(@restaurant)
  end
  
  private

  def meal_params
    params.require(:meal).permit(:name, :desc, :price, :restaurant_id, :meal_type, :available, :code)
  end

  def set_meal
    @meal = Meal.find(params[:id])
  end

end

app/controllers/api/v1/meals_controller.rb
class Api::V1::MealsController < Api::V1::BaseController
  before_action :authenticate_with_token!

  # restaurant to enable meal in the menu
  def enable
    meal = current_user.restaurant.meals.find(params[:id])
    meal.update(available: true)
    render json: {is_success: true}
  end

  # restaurant to disable meal in the menu
  def disable
    meal = current_user.restaurant.meals.find(params[:id])
    meal.update(available: false)
    render json: {is_success: true}
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, except: [:create, :index]

  def index
    @foods = current_user.restaurant.meals.where(meal_type: 0)
    @drinks = current_user.restaurant.meals.where(meal_type: 1)
    @meal = Meal.new
  end

  def create
    @meal = current_user.restaurant.meals.build(meal_params)
    if @meal.save
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def show

  end

  def update
    if @meal.update(meal_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_to meals_path
  end

  def enable
    @meal.update(available: true)
    flash[:notice] = "Enable..."
    redirect_back(fallback_location: request.referer)
  end

  def disable
    @meal.update(available: false)
    flash[:notice] = "Disable..."
    redirect_back(fallback_location: request.referer)
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :desc, :price, :meal_type, :available, :code)
  end

  def set_meal
    @meal = Meal.find(params[:id])
  end

end

app/views/meals/_form.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-normal btn-success" data-toggle="modal" data-target="#myModal">
  Add Meal
</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-left">Add Meal</h4>
      </div>
      <div class="modal-body">
        <%= form_for @meal do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, autofocus: true, placeholder: "Meal Name", class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <label>Description</label>&nbsp;<small>(optional)</small>
          <%= f.text_area :desc, autofocus: true, placeholder: "Meal Description", class: "form-control" %>
        </div>

        <div class="form-group">
          <label>Meal Code</label>&nbsp;<small>(optional)</small>
          <%= f.text_field :code, autofocus: true, placeholder: "Meal Code", class: "form-control" %>
        </div>

        <div class="form-group">
          <label>Type</label>
          <%= f.select :meal_type, ["Food", "Drink"], prompt: "Select...", class: "form-control "%>
        </div>

        <div class="form-group">
          <label>Price</label>
          <%= f.text_field :price, autofocus: true, placeholder: "Meal Price", class: "form-control", required: true %>
        </div>

        <div class="text-center">
          <%= f.submit "Submit", class: "btn btn-normal btn-block" %>
        </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/meals/index.html.erb
<div class="row">
    <div class="col-md-6"></div>
    <div class="col-md-6">
      <div class="pull-right">
        <%= render partial: "form" %>
      </div>
    </div>
</div><br>


<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Foods
        <br>
      </div>
      <div class="panel-body">
        <div>
          <div style="overflow-x:auto;">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Code</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Price</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <%@foods.each_with_index do |food, index|%>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= !food.code.blank? ? food.code : "N/A" %></td>
                  <td><%= link_to food.name, meal_path(food) %></td>
                  <td><%= !food.desc.blank? ? food.desc : "N/A" %></td>
                  <td><%= food.price %></td>
                  <td>
                    <% if food.available %>
                      <%= link_to "Disable", disable_meal_path(food), method: :post, class: "btn-link" %>
                    <% else %>
                      <%= link_to "Enable", enable_meal_path(food), method: :post, class: "btn-link" %>
                    <% end %>
                  </td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Drinks
        <br>
      </div>
      <div class="panel-body">
        <div>
          <div style="overflow-x:auto;">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Code</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Price</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <%@drinks.each_with_index do |drink, index|%>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= !drink.code.blank? ? drink.code : "N/A" %></td>
                  <td><%= link_to drink.name, meal_path(drink) %></td>
                  <td><%= !drink.desc.blank? ? drink.desc : "N/A" %></td>
                  <td><%= drink.price %></td>
                  <td>
                    <% if drink.available %>
                      <%= link_to "Disable", disable_meal_path(drink), method: :post, class: "btn-link" %>
                    <% else %>
                      <%= link_to "Enable", enable_meal_path(drink), method: :post, class: "btn-link" %>
                    <% end %>
                  </td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Manage Meal
      </div>
      <div class="panel-body" style="padding-left:80px;padding-right:80px;">
        <%= form_for @meal do |f| %>
        <div class="row">
          <div class="col-md-12">
            <h4>Meal Details</h4>
            <div class="row">
              <div class="form-group pull-in clearfix">
                <div class="col-md-4">
                  <label>Name</label>
                  <%= f.text_field :name, class: 'form-control', placeholder:"Meal name", type:"text", required: true %>
                </div>
                <div class="col-md-4">
                  <label>Price</label>
                  <%= f.text_field :price, class: 'form-control', placeholder:"Meal price", type:"text", required: true %>
                </div>
                <div class="col-md-4">
                  <label>Type</label>
                  <%= f.select :meal_type, ['Food','Drink'], required: true, class: "form-control" %>
                </div>
              </div>
            </div>
            <hr>
            <h4>Meal Description</h4>
            <div class="row">
              <div class="form-group pull-in clearfix">
                <div class="col-md-12">
                  <label>Description</label>
                  <%= f.text_field :desc, class: 'form-control', placeholder:"Meal Description", type:"text" %>
                </div>
              </div>
              <div class="form-group pull-in clearfix">
                <div class="col-md-4">
                  <label>Available</label>
                  <%= f.select :available, [['Yes', true],['No', false]], required: true, class: "form-control" %>
                </div>
                <div class="col-md-4">
                  <label>Meal Code</label>
                  <%= f.text_field :code, autofocus: true, placeholder: "Meal Code", class: "form-control" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-12">
          <span><%= link_to "Back", meals_path, class: "btn btn-default"%></span>
          <span><%= f.submit "Update", class: "btn btn-normal btn-form"%></span>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>